# Basic Config
server.port=8080

# Database
spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/career_db
spring.datasource.username=root
spring.datasource.password=root@123
spring.jpa.hibernate.ddl-auto=update

# Email setup
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayushmistry0054@gmail.com
spring.mail.password=Ayush@2406
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.allow-circular-references=true

wit.ai.token=YOUR_WIT_AI_SERVER_ACCESS_TOKEN
